### ISSUE TITLE
[功能请求] 能否支持自定义转发途径

### ISSUE THREAD

**Issue by jqtmviyu** [lkiuyu/DbusSmsForwardCPlus#1]
可以把发件人和短信内容传给自定义shell脚本, 自行组装

例如:  企微的机器人支持webhook调用, 还支持类似mipush的后台推送

**Comment by lkiuyu** [comment]
理论可行，调用指定路径的shell脚本并传递参数，不过目前没空做这个功能，等有空我看看

**Comment by lkiuyu** [comment]
可以看一下最新版本，已经支持转发到自定义的shell脚本
