### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by xqa** [lkiuyu/DbusSmsForwardCPlus#2]
那个api发送短信加了区号就不得行，我的是giff卡，发国内加+86没反应

**Comment by lkiuyu** [comment]
不一定是程序问题，程序主体是使用dbus消息和设备的modemManager进行通讯从而进行相关操作，短信发送实际是由设备的modemManager执行，发短信失败有可能有多种原因，并且由于我本人没有国外卡，相关测试我这无法进行，需要你那边自行测试，这里可以给你几个测试的方向

最容易出现的一种是modem并没有成功注册并连接移动网路，你可以使用命令mmcli -m 0查看设备modem信息，看是否成功connect上网络，如果你确定你的modem已经成功注册并连接到了移动网络，那你可以使用如下的modemManager的命令行

mmcli -m 0 --messaging-create-sms="text ='短信内容', number = '短信号码'"

来创建一条待发送的短信
使用如下命令列出设备所有短信
mmcli -m 0 --messaging-list-sms

找到后缀为unknown的那条，这就是你刚刚创建的短信，看看它的编号是多少，接着执行以下命令发送短信

mmcli -s 编号 --send

发送短信，看看你测试的加了86区号的短信能否发送成功，如果使用modemManager的命令发送短信成功，那就可以定位是我这程序与modemManager的交互出了问题，如果使用命令发送短信不成功，则可以认定为是设备modemManager不支持，那我这程序也是无能为力的

**Comment by xqa** [comment]
根据你的说明，我用
mmcli -m 0 --messaging-create-sms="text ='短信内容', number = '短信号码'"
mmcli -m 0 --messaging-list-sms
mmcli -s 编号 --send
这几个成功发送的短信到我的国内手机
我在我手机号前面加了+86。 比如 
mmcli -m 0 --messaging-create-sms="text ='test', number = '+8617712341234'"

所有应该是交互有点问题

**Comment by lkiuyu** [comment]
那这个我有空排查下，你也可以试试用转发程序命令行提供的短信发送功能测试一下，运行程序选择发送短信就行，看看能不能行，如果转发程序提供的短信发送功能可以发送短信的话就可以初步确定是api接口部分的问题了，如果程序提供的短信发送功能也不能发短信的话那估计是短信发送逻辑有了bug

**Comment by xqa** [comment]
这个命令行的也可以发送成功
知道怎么发就行了，我注意是半年要发短信保号一次
:sob::sob::sob: 这个卡发短信0.3英镑一条，难受
我怀疑那个api应该是号码前面的'+86'区号的编码问题，c++看不太懂

**Comment by lkiuyu** [comment]
那我大概知道为什么了，估计真是编码问题，短信号码那边我没有添加url编码，这个+在参数传递过程中估计变成别的了，后期更新一版改进一下，把web页面调用接口的时候把电话号码也url编码一下

**Comment by xqa** [comment]
![image](https://github.com/lkiuyu/DbusSmsForwardCPlus/assets/107579458/6e0dfbec-638c-41ff-811f-7fa7a3bca9a3)
tg转发也有点问题。
tg发送消息后的返回值是个json ，感觉像是解析请求返回值的问题(想试着看懂c++，胡说的）

**Comment by lkiuyu** [comment]
检查一下配置的参数是否正确，以及网络环境是否畅通，没有畅通的网络环境的话建议使用自建tg代理来进行转发

**Comment by xqa** [comment]
我参数正确的我本地拼接url都能直接访问，就是用的代理转发的

**Comment by lkiuyu** [comment]
那我后面排查下，可能返回参数有更新

**Comment by lkiuyu** [comment]
方便贴一下你的配置吗，我怀疑你的tg参数配置有问题，我这本地测试tg转发没问题
![af85799633eb2e73ff60cf9509ba437](https://github.com/lkiuyu/DbusSmsForwardCPlus/assets/8980816/1ab5b016-ecf5-44e7-aa2a-09378c7ee558)

**Comment by xqa** [comment]
https://t.me/CoffDream
你加我tg，我tg发你嘛，不好公开发

**Comment by lkiuyu** [comment]
最新版本已修复
