### ISSUE TITLE
大佬能编译下这个cpu型号的包吗

### ISSUE THREAD

**Issue by cyclestudy** [lkiuyu/DbusSmsForwardCPlus#3]
aarch64_cortex-a53

**Comment by lkiuyu** [comment]
你这个不就是arm64的吗，如果你是debian系的系统应该可以直接用成品的吧，如果你是OpenWrt的话直接把源码克隆到本地OpenWrt的package目录，然后编译配置菜单里把这个勾选上编译就行了，而且我不清楚你具体是什么设备，我这个程序目前只适用于使用modemManager管理4gModem的设备，其他的不兼容

**Comment by cyclestudy** [comment]
> 你这个不就是arm64的吗，如果你是debian系的系统应该可以直接用成品的吧，如果你是OpenWrt的话直接把源码克隆到本地OpenWrt的package目录，然后编译配置菜单里把这个勾选上编译就行了，而且我不清楚你具体是什么设备，我这个程序目前只适用于使用modemManager管理4gModem的设备，其他的不兼容

NRadio C8-660-512M
行吧，我以为通用的
