### ISSUE TITLE
Method call failed: Unknown method 

### ISSUE THREAD

**Issue by luqizhi666** [lkiuyu/DbusSmsForwardCPlus#4]
Method call failed: Unknown method

**Comment by lkiuyu** [comment]
我建议你提问题的时候可以带点截图，终端运行时候的完整命令以及报错都可以截图到里面，这样可以方便我排查问题，目前你可以先排查一下你的modem运行正不正常，modem运行不正常的话我的程序也是没法用的，可以使用命令mmcli -m 0看看modem的状态

**Comment by luqizhi666** [comment]
![图片](https://github.com/lkiuyu/DbusSmsForwardCPlus/assets/78798951/d851b586-7931-47b0-ac93-bb629546eb58)
好的，请问这样是正常的吗

**Comment by lkiuyu** [comment]
可以截完整的图吗，我需要完整的内容，你可以把一些关键隐私信息遮住

**Comment by lkiuyu** [comment]
顺便你可以把你执行短信转发程序的终端命令也截图，截完整的，我这看看

**Comment by lkiuyu** [comment]
刚刚我又看了下你上面的截图，你的modem状态是searching状态，压根就没能联网成功，所以说还是有点问题的，建议先确保modem能正常使用再运行我这个程序
