### ISSUE TITLE
 可以对接webhook么？发送json

### ISSUE THREAD

**Issue by wanghlstar** [lkiuyu/DbusSmsForwardCPlus#5]
可以对接webhook么？发送json 例如 {"text":"[msg]"} 
还是 shell 的方式通过 curl 调 webhook地址发post ？

**Comment by lkiuyu** [comment]
你可以看看调用自定义shell脚本转发的渠道，我项目里有写一个shell脚本转发至pushplus的例子，里面就是使用的curl，你可以参考这个写，具体shell里面的参数定义readme里有

**Comment by wanghlstar** [comment]
感谢感谢
那个 企微的机器人~~  
也用shell  curl 可以么？

**Comment by lkiuyu** [comment]
这我不清楚，我程序对接的企业微信自定义应用，机器人不清楚什么对接原理，你可以自己尝试一下，理论你用命令行能实现，那shell就能实现

**Comment by wanghlstar** [comment]
嗯，好的，感谢 大佬 如此优秀项目 
企业微信自定义应用 得可信域名和 ip ~~ 要费点事 ~~

**Comment by lkiuyu** [comment]
估计是企业微信这段时间开始做限制了😂，之前对接这个的时候随便用，没这些限制
