### ISSUE TITLE
Bark 转发出错

### ISSUE THREAD

**Issue by GuaiMiu** [lkiuyu/DbusSmsForwardCPlus#8]
错误提示
![image](https://github.com/user-attachments/assets/eea3d3a5-595a-4006-a3b5-fbafc08f69ff)
config.txt
![image](https://github.com/user-attachments/assets/452d661d-c82e-43a5-8514-05963aee1c8c)
烦请大佬，给看看。

**Comment by lkiuyu** [comment]
![image](https://github.com/user-attachments/assets/1125e5f7-f79d-48eb-97b0-9a7b67ac8035)
我这测试官方的服务器没问题，可以考虑网络问题或者自部署的服务返回参数和官方不一致

**Comment by GuaiMiu** [comment]
我找到原因了，waf把这个给拦截了，麻烦大佬了。
